apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: my-quotaspecbinding
  namespace: istio-system
spec:
  quotaSpecs:
  - name: my-qspec
    namespace: istio-system
  services:
  # リストしたServiceに対する通信にquotaspecがバインドされる
  - name: my-api
    namespace: test
