apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: my-quotaspecbinding
  namespace: istio-system
spec:
  quotaSpecs:
  - name: my-quotaspec
    namespace: istio-system
  services:
  - name: httpbin
    namespace: test
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: my-quotaspec
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: my-instance
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: my-memquota
    instances:
    - my-instance
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: my-instance
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      destination: destination.labels["app"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: my-memquota
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: my-instance.instance.istio-system
      maxAmount: 100
      validDuration: 5s
      overrides:
      - dimensions:
          destination: httpbin
        maxAmount: 1
        validDuration: 5s
