apiVersion: v1
kind: Pod
metadata:
  name: cpu-500m
spec:
  containers:
  - name: example
    image: alpine:3.11
    command: ["sh", "-exc", "apk add --no-cache stress-ng && exec stress-ng --cpu 0"]
    resources:
      requests:
        cpu: 250m
      limits:
        cpu: 500m
