apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow
  template:
    metadata:
      labels:
        app: langflow
    spec:
      containers:
      - name: langflow
        image: langflowai/langflow:latest
        ports:
        - containerPort: 7860
        args: ["--host", "0.0.0.0", "--port", "7860"]
        # env:
        # - name: DATABASE_URL
        #   value: "postgresql://user:password@vector:5432/database"
---
apiVersion: v1
kind: Service
metadata:
  name: langflow
spec:
  type: ClusterIP
  ports:
  - port: 7860
    targetPort: 7860
  selector:
    app: langflow


