apiVersion: v1
kind: Pod
metadata:
  name: host-path-read-only
spec:
  containers:
  - name: example
    image: alpine:3.11
    command: ["sh", "-xc", "touch /foo/this-fails; touch /foo/tmp/this-may-succeed"]
    volumeMounts:
    - mountPath: /foo
      name: foo
      readOnly: true
  volumes:
  - name: foo
    hostPath:
      path: /
  restartPolicy: Never
