apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-128m
spec:
  containers:
  - name: example
    image: centos:8.1.1911
    command: ["bash", "-exc", "for (( i=0; i < 1024; i++)); do dd if=/dev/urandom of=/tmp/foo bs=1M count=1 conv=notrunc oflag=append; du -hs /tmp; sleep 1; done"]
    resources:
      limits:
        ephemeral-storage: 128Mi
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  volumes:
  - name: tmp
    emptyDir: {}
