apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shopping-developers
  namespace: payment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pod-role
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: system-tools
