apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Namespace # またはServer、User、SourceAndObject
  qps: 50
  burst: 100
  cacheSize: 2000 # Serverでは指定しない
- type: User
  qps: 30
  burst: 60
  cacheSize: 100
- type: Server
  qps: 100
  burst: 200
- type: SourceAndObject
  qps: 20
  burst: 50
  cacheSize: 80
