apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: git
        image: alpine:3.10
        command: ["sh", "-c", "apk add --no-cache git openssh-client && git clone git@git.example.com:example/foo.git /workspace"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: secret-ssh
          mountPath: /root/.ssh
          readOnly: true
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:v0.13.0
        args: ["--destination=asia.gcr.io/example/foo"]
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp.json
        volumeMounts:
        - name: workspace
          mountPath: /workspace
          readOnly: true
        - name: secret-gcp
          mountPath: /secret
          readOnly: true
      volumes:
      - name: workspace
        emptyDir: {}
      - name: secret-ssh
        secret:
          secretName: kaniko-secret-ssh
          defaultMode: 0400
      - name: secret-gcp
        secret:
          secretName: kaniko-secret-gcp
