apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-for-bob
  namespace: payment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-for-bob
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
