apiVersion: v1
kind: Pod
metadata:
  name: memory-2g
spec:
  containers:
  - name: example
    image: alpine:3.11
    command: ["sh", "-exc", "apk add --no-cache stress-ng && exec stress-ng --vm 0 --vm-bytes 4G"]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi
