apiVersion: v1
kind: Pod
metadata:
  name: test-disable-sa-automount
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
