apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: dev
  namespace: development
spec:
  # 指定されたtargetでmTLSのリクエストを受ける設定が適用される
  targets:
  - name: my-service
  peers:
  - mtls: {}
