apiVersion: secrets-store.csi.k8s.com/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-secret-via-vault
spec:
  provider: vault
  parameters:
    roleName: "csi-test-role"
    vaultAddress: "http://127.0.0.1:8200" #実際のVaultのアドレスに置き換える
    objects:  |
      array:
        - |
          objectPath: "/csi-test"
          objectName: "my-secret"
          objectVersion: ""
