apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: nginx
    volumeMounts:
    - name: my-secret
      mountPath: /etc/my-app/secret
      readOnly: true
  volumes:
  - name: my-secret
    secret:
      secretName: my-secret
