apiVersion: v1
kind: Pod
metadata:
  name: dood
spec:
  containers:
  - name: docker
    image: docker:19.03.3
    args: ["docker", "info"]
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  restartPolicy: Never
